name: Java CI

on: [push]

jobs:
  build-linux-jdk8-fx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install xvfb
    - name: Build with Ant
      run: xvfb-run ant test-javase


    - name: Fetch JavaDoc Source Embed
    - uses: actions/download-artifact@v2
      with:
        name: JavaDocSourceEmbed-1.0-SNAPSHOT.jar
  
    - name: Build Release
      run: ant -noinput -buildfile CodenameOne/build.xml weeklyLibUpdate

    - name: Upload updatedLibs.zip
      uses: actions/upload-artifact@v2
      with:
        name: updatedLibs.zip
        path: updatedLibs.zip

    - name: Upload JavaDoc Zip
      uses: actions/upload-artifact@v2
      with:
        name: CodenameOne_SRC.zip
        path: build/CodenameOneDist/CodenameOne/demos/CodenameOne_SRC.zip
